
version: 2

models:
  - name: int_base_product_sales
    description: "Base-level product sales and revenue metrics."
    columns:
      - name: product_id
        description: "Unique product identifier."
        tests:
          - not_null
      - name: total_quantity_sold
        description: "Total number of units sold."
      - name: total_revenue
        description: "Total revenue from the product."


  - name: int_customer_order_summary
    description: "Customer-level total orders and spending."
    columns:
      - name: customer_id
        description: "Customer ID."
        tests:
          - unique
          - not_null
      - name: total_orders
        description: "Total number of orders placed by the customer."
      - name: total_spent
        description: "Total amount spent by the customer."


  - name: int_customer_product_interaction
    description: "Tracks how each customer interacted with products."
    columns:
      - name: customer_id
        description: "Customer ID."
        tests:
          - not_null
      - name: product_id
        description: "Product ID."
        tests:
          - not_null
      - name: times_purchased
        description: "How many times the product was bought by the customer."


  - name: int_orders
    description: "Order-level cleaned data enriched with customer and date info."
    columns:
      - name: order_id
        description: "Unique order ID."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer who placed the order."
        tests:
          - not_null
      - name: order_date
        description: "Date when order was placed."
        tests:
          - not_null


  - name: int_rfm_calculated
    description: "RFM base metrics for each customer."
    columns:
      - name: customer_id
        description: "Customer ID."
        tests:
          - not_null
          - unique
      - name: recency_days
        description: "Days since last order."
      - name: frequency
        description: "Number of orders."
      - name: monetary
        description: "Total spend by customer."


  - name: int_rfm_rank_calc
    description: "Calculated RFM score for each customer."
    columns:
      - name: customer_id
        description: "Customer ID."
        tests:
          - not_null
      - name: rfm_score
        description: "Combined RFM score used for ranking."


  - name: int_top_20_rfm_customers
    description: "Top 20 customers based on RFM score and spend."
    columns:
      - name: customer_id
        description: "Top performing customer ID."
        tests:
          - not_null
      - name: rfm_score
        description: "RFM score used for filtering top customers."
      - name: total_spent
        description: "Total spend by customer."
