version: 2


models:
  - name: int_orders
    description: "Combines orders with order items, payments, and customer info"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer who placed the order"
        tests:
          - not_null
      - name: order_date
        description: "Date the order was placed"
      - name: product_id
        description: "Product ID"
      - name: category
        description: "Product category"
      - name: payment_method
        description: "Method of payment"
      - name: quantity
        description: "Total quantity ordered"
      - name: total_price
        description: "Total price (quantity * unit price)"


  - name: int_customer_order_summary
    description: "Summary of each customer's order behavior"
    columns:
      - name: customer_id
        description: "Unique customer ID"
        tests:
          - not_null
          - unique
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name"
      - name: total_orders
        description: "Total number of orders placed"
      - name: total_items
        description: "Total items purchased"
      - name: total_spent
        description: "Total amount spent"
      - name: first_order_date
        description: "Date of first order"
      - name: last_order_date
        description: "Date of most recent order"
      - name: avg_order_value
        description: "Average order value"
      - name: customer_segment
        description: "Customer classification (e.g., New, Returning, etc.)"


  - name: int_customer_product_interaction
    description: "Tracks customer's interaction with products"
    columns:
      - name: customer_id
        description: "Customer ID"
        tests:
          - not_null
      - name: product_id
        description: "Product purchased"
        tests:
          - not_null
      - name: total_quantity
        description: "Total quantity of this product purchased"
      - name: total_spent
        description: "Total spent on this product"
      - name: last_purchase_date
        description: "Most recent purchase of this product"


  - name: int_rfm_rank_calc
    description: "RFM score calculation and ranking for each customer into meaningful buckets"
    columns:
      - name: customer_id
        description: "Customer ID"
        tests:
          - not_null
          - unique
      - name: recency
        description: "Days since last order"
      - name: frequency
        description: "Total orders placed"
      - name: monetary
        description: "Total money spent"
      - name: rfm_score
        description: "Concatenated RFM score (e.g., 555)"
        tests:
          - not_null
      - name: rfm_segment
        description: "Customer segment derived from RFM score"
        tests:
          - not_null
