version: 2

models:

  - name: int_customers
    description: "Cleaned and enriched customer details"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null

  - name: int_rfm_calculated
    description: "RFM metrics for each customer"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: recency
        tests:
          - not_null

  - name: int_rfm_ranked
    description: "RFM ranks assigned based on calculated metrics"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: rfm_score
        tests:
          - not_null

  - name: int_customer_order_summary
    description: "Summarizes customer orders, total spending, and order metrics"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: total_spent
        tests:
          - not_null
      - name: total_orders
        tests:
          - not_null

  - name: int_product_sales_summary
    description: "Summarizes product sales, revenue, and customer engagement"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: total_units_sold
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
