version: 2

models:
  - name: int_orders
    description: Cleans and enriches raw orders data with additional computed fields
    columns:
      - name: order_id
        description: Unique identifier for the order
        tests:
          - not_null
          - unique

      - name: customer_id
        description: Customer placing the order
        tests:
          - not_null

      - name: order_date
        description: Date of the order
        tests:
          - not_null

      - name: order_amount
        description: Total amount of the order
        tests:
          - not_null

  - name: int_rfm_calculated
    description: Calculates RFM metrics (Recency, Frequency, Monetary) for each customer
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - not_null
          - unique

      - name: last_order_date
        description: Most recent order date for the customer
        tests:
          - not_null

      - name: recency
        description: Days since last order
        tests:
          - not_null

      - name: frequency
        description: Number of orders placed by the customer
        tests:
          - not_null

      - name: monetary
        description: Total amount spent by the customer
        tests:
          - not_null

  - name: int_rfm_ranked
    description: Adds ranking to customers based on monetary contribution using row_number
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - not_null
          - unique

      - name: contribution
        description: Monetary value used for ranking

      - name: rno
        description: Row number of the customer based on descending contribution
        tests:
          - not_null
