name: 'e_commerce_analytics_project'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  e_commerce_analytics_project:
    staging:
      +schema: "{{target.name}}_staging"
    intermediate:
      +schema: "{{target.name}}_intermediate"
    mart:
      +schema: "{{target.name}}_mart"

