--path: models/staging/schema.yml
version: 2

models:
  - name: stg_customers
    description: "Staging model for raw customer data"
    columns:
      - name: customer_id
        description: "Primary key for the customer"
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: email
        description: "Customer's email address"
      - name: gender
        description: "Gender of the customer"
      - name: customer_created_at
        description: "Timestamp when the customer was created"
      - name: customer_updated_at
        description: "Timestamp when the customer record was last updated"

  - name: stg_orders
    description: "Staging model for raw order data"
    columns:
      - name: order_id
        description: "Primary key for the order"
      - name: customer_id
        description: "Foreign key referring to customer"
      - name: order_date
        description: "Date when the order was placed"
      - name: order_amount
        description: "Total amount of the order"
      - name: status
        description: "Current status of the order"
      - name: created_at
        description: "Timestamp when the order was created"
      - name: updated_at
        description: "Timestamp when the order was last updated"

  - name: stg_payments
    description: "Staging model for raw payments data"
    columns:
      - name: payment_id
        description: "Primary key for the payment"
      - name: order_id
        description: "Foreign key referring to order"
      - name: payment_date
        description: "Date when the payment was made"
      - name: mode_of_payment
        description: "Mode used for the payment (e.g. card, UPI)"
      - name: payment_status
        description: "Current payment status"
      - name: created_payment_at
        description: "Timestamp when the payment record was created"
      - name: updated_payment_at
        description: "Timestamp when the payment record was updated"
