version: 2

sources:
  - name: datafeed
    database: ecomm_analytics_db
    schema: datafeed
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_order_items
      - name: raw_products
      - name: raw_payments

models:
  - name: stg_customers
    description: "Staging model for customers"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_orders
    description: "Staging model for orders"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

  - name: stg_order_items
    description: "Staging model for order items"
    columns:
      - name: order_item_id
        tests:
          - not_null
          - unique

  - name: stg_products
    description: "Staging model for products"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: stg_payments
    description: "Staging model for payments"
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
