version: 2

models:
  - name: top_customers
    description: >
      Shows top 20 customers based on contribution with insights on activity and value.
      Derived from RFM metrics and ranked data.

    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - not_null
          - unique

      - name: contribution
        description: Total monetary contribution by the customer

      - name: recency
        description: Days since last purchase

      - name: frequency
        description: Number of purchases made by the customer

      - name: monetary
        description: Total spend by the customer

      - name: rno
        description: Row number of customer based on contribution ranking

      - name: customer_activity_status
        description: Categorized as 'Highly Active', 'Active', or 'Inactive' based on recency

      - name: customer_value_segment
        description: Categorized as 'High Value' or 'Low Value' based on contribution threshold
