version: 2

models:

  - name: mart_top_customers
    description: "Top 20 customers ranked by RFM and contribution"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: contribution
        description: "Total amount contributed by the customer"
      - name: recency
        description: "Number of days since last purchase"
      - name: frequency
        description: "Number of purchases made by the customer"
      - name: monetary
        description: "Total money spent by the customer"
      - name: rno
        description: "Rank of the customer based on RFM and contribution"
      - name: customer_activity_status
        description: "Activity status based on recency (Highly Active / Active / Inactive)"
      - name: customer_value_segment
        description: "Segment based on contribution (High Value / Low Value)"

  - name: mart_customer_360
    description: "Final customer 360 view with RFM, top product, order summary, and segments"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: recency
        description: "Number of days since last purchase"
      - name: frequency
        description: "Number of purchases made by the customer"
      - name: monetary
        description: "Total money spent by the customer"
      - name: rfm_rank
        description: "Combined RFM ranking score"
      - name: customer_activity_status
        description: "Activity status based on recency"
      - name: customer_value_segment
        description: "Customer value segment based on spend and frequency"
      - name: top_product_id
        description: "Most purchased product by the customer"
      - name: total_quantity
        description: "Total quantity of the top product bought"
      - name: total_spent_on_product
        description: "Total spend on the top product"
      - name: total_orders
        description: "Total number of orders placed"
      - name: contribution
        description: "Total revenue contributed by the customer"

  - name: customer_segmentation_mart
    description: "Final mart with churn status, behavioral segment, and combined segmentation based on RFM scores"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: recency
        description: "Days since last purchase"
      - name: frequency
        description: "Total number of purchases"
      - name: monetary
        description: "Total spending amount"
      - name: rfm_score
        description: "Combined RFM score from intermediate model"
      - name: churn_status
        description: "Customer churn classification"
      - name: behavioral_segment
        description: "Behavioral segment based on frequency and monetary"
      - name: combined_segment
        description: "Combined churn and behavioral label
